INSERT INTO crags (crag_name, region_name) 
VALUES ('Animal Crackers Wall',            'Muir Valley'),
       ('The Arsenal',                     'Muir Valley'),
       ('Bibliothek',                      'Muir Valley'),
       ('The Boneyard',                    'Muir Valley'),
       ('The Bowling Alley',               'Muir Valley'),
       ('Bruisebrothers Wall',             'Muir Valley'),
       ('Coyote Cliff',                    'Muir Valley'),
       ('The Fire Wall',                   'Muir Valley'),
       ('Great Arch',                      'Muir Valley'),
       ('Great Wall',                      'Muir Valley'),
       ('Guide Wall',                      'Muir Valley'),
       ('The Hideout',                     'Muir Valley'),
       ('Indy Wall',                       'Muir Valley'),
       ('Inner Sanctum',                   'Muir Valley'),
       ('Ivory Tower',                     'Muir Valley'),
       ('Land Before Time Wall',           'Muir Valley'),
       ('Midnight Surf',                   'Muir Valley'),
       ('Persepolis',                      'Muir Valley'),
       ('Practice Wall',                   'Muir Valley'),
       ('The Sanctuary',                   'Muir Valley'),
       ('Shawnee Shelter',                 'Muir Valley'),
       ('Slab City',                       'Muir Valley'),
       ('Solarium',                        'Muir Valley'),
       ('South Side',                      'Muir Valley'),
       ('The Stadium',                     'Muir Valley'),
       ('The Stronghold',                  'Muir Valley'),
       ('Sunbeam Buttress',                'Muir Valley'),
       ('Sunnyside',                       'Muir Valley'),
       ('Tectonic Wall and Johnny''s Wall','Muir Valley'),
       ('Washboard Wall',                  'Muir Valley');